/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aspirante: typeof import('./src/components/seleccion/Aspirante.vue')['default']
    Becas: typeof import('./src/components/becas/Becas.vue')['default']
    Formulario: typeof import('./src/components/seleccion/Formulario.vue')['default']
    Grupos: typeof import('./src/components/grupos/Grupos.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/access/login.vue')['default']
    NavBar: typeof import('./src/components/loyout/NavBar.vue')['default']
    Personal: typeof import('./src/components/personal/Personal.vue')['default']
    Resultados: typeof import('./src/components/loyout/Resultados.vue')['default']
    Rol: typeof import('./src/components/rol/rol.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seleccion: typeof import('./src/components/seleccion/Seleccion.vue')['default']
    Usuario: typeof import('./src/components/usuario/Usuario.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
